# Generated by Django 4.0.5 on 2022-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('new_price', models.CharField(max_length=100)),
                ('fullprice', models.CharField(max_length=100)),
                ('sizes', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('art', models.CharField(max_length=100)),
            ],
        ),
    ]
